{{/*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}
{{- $values := .Values }}
{{- range $i, $issuer := .Values.certIssuers }}
{{- $s := $issuer.name }}
{{- $d := $issuer.duration }}
{{- $p := $issuer.password }}
apiVersion: v1
data:
  password: {{ $p | default "changeme" }}
kind: Secret
metadata:
  name: {{ template "redpanda.fullname" $ }}-{{ $s }}-cert-keystore
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "redpanda.fullname" $ }}-{{ $s }}-cert
spec:
  dnsNames:
  - {{ template "redpanda.fullname" $ }}-cluster.{{ (include "redpanda.internal.domain" $) | trimSuffix "." }}
  - '*.{{ template "redpanda.fullname" $ }}-cluster.{{ (include "redpanda.internal.domain" $) | trimSuffix "." }}'
  - {{ (include "redpanda.internal.domain" $) | trimSuffix "." }}
  - '*.{{ (include "redpanda.internal.domain" $) | trimSuffix "." }}'
  - {{ (first $values.config.redpanda.kafka_api).external.subdomain }}
  - {{ printf "*.%s" (first $values.config.redpanda.kafka_api).external.subdomain | squote }}
  duration: {{ $d | default "43800h" }}
  isCA: false
  commonName: {{ template "redpanda.fullname" $ }}-{{ $s }}-cert
  secretName: {{ template "redpanda.fullname" $ }}-{{ $s }}-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ template "redpanda.fullname" $ }}-{{ $s }}-root-issuer
    kind: Issuer
    group: cert-manager.io
  keystores:
    jks:
      create: true
      passwordSecretRef:
        key: password
        name:  {{ template "redpanda.fullname" $ }}-{{ $s }}-cert-keystore
    jks:
      create: true
      passwordSecretRef:
        key: password
        name: {{ template "redpanda.fullname" $ }}-{{ $s }}-cert-keystore 
---
{{- end }}
